apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: hospital
type: Opaque
stringData:
  PATIENT_DB_USER: postgres
  PATIENT_DB_PASSWORD: postgres123
  DOCTOR_DB_USER: postgres
  DOCTOR_DB_PASSWORD: postgres123
  APPOINTMENT_DB_USER: postgres
  APPOINTMENT_DB_PASSWORD: postgres123
  BILLING_DB_USER: postgres
  BILLING_DB_PASSWORD: postgres123
  KEYCLOAK_DB_USER: keycloak
  KEYCLOAK_DB_PASSWORD: keycloak123

