apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: hospital
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

