apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: hospital
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: hospital/appointment-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5003
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres-appointment;Port=5432;Database=appointmentdb;Username=postgres;Password=postgres123
            - name: Kafka__BootstrapServers
              value: kafka:9092
            - name: Eureka__Client__ServiceUrl
              value: http://eureka-service:8761/eureka/
            - name: Keycloak__Authority
              value: http://keycloak:8080/realms/hospital
            - name: Keycloak__Audience
              value: hospital-api
          ports:
            - containerPort: 5003
          readinessProbe:
            httpGet:
              path: /api/appointments/health
              port: 5003
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/appointments/health
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 20
