apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: hospital
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: hospital/doctor-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5002
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres-doctor;Port=5432;Database=doctordb;Username=postgres;Password=postgres123
            - name: Kafka__BootstrapServers
              value: kafka:9092
            - name: Eureka__Client__ServiceUrl
              value: http://eureka-service:8761/eureka/
            - name: Keycloak__Authority
              value: http://keycloak:8080/realms/hospital
            - name: Keycloak__Audience
              value: hospital-api
          ports:
            - containerPort: 5002
          readinessProbe:
            httpGet:
              path: /api/doctors/health
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/doctors/health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 20

